### PR TITLE
dockerized

### PR DESCRIPTION
**Pull request by st3b1t**
improvable but it works!
To simplify the work of those who want to integrate fbbe in other contexts.

```bash
cd ./docker
docker compose up
```

### CODE REVIEW

**Comment by RCasatta** [comment]
Sorry if I didn't document it, but there is a docker image built with nix containing the fbbe executable that is incredibly small https://hub.docker.com/layers/xenoky/fbbe/latest/images/sha256-e95e68e02a57188543ed008b178abfe0b560d9ba466b5792d38f302ebf82ec6c?context=explore

you need nix installed to build it with:

```
nix build .#dockerImage
./result | docker load
```

I think It may be interesting to have also the docker way to build it? and document both?

**Comment by st3b1t** [comment]
@RCasatta I think that a simple Dockerfile could be a very useful thing for other contributors to disseminate your project, for those who don't want or who can't use nix.
Anyway wow! really amazing optimization with nix it's great in enterprise environments

**Comment by st3b1t** [comment]
however using the last version of nix, the command  `nix-build` doesn't work and what mean `.#dockerImage`?
`default.nix': No such file or directory`

**Comment by RCasatta** [comment]
> @RCasatta I think that a simple Dockerfile could be a very useful thing for other contributors to disseminate your project, for those who don't want or who can't use nix.

I can merge also the dockerfile, but could you please add a section of the Readme that shows the 2 ways of building the docker?

> however using the last version of nix, the command nix-build doesn't work 
default.nix': No such file or directory

Note that `nix-build` and `nix build` are different commands, the latter is the new still-experimental way.

> what mean .#dockerImage?

this notation means to look at the local `flake.nix` and build the #dockerImage package defined here https://github.com/RCasatta/fbbe/blob/55a80c61ad8e30964eb2db5b4f3b7d3b1f0c9b01/flake.nix#L47


In the PR there are commits already merged and a merge commit that needs to be removed.

**Comment by st3b1t** [comment]
I am trying to build this Dockerfile with `nix` but it doesn't seem like a very understandable tool to use :)
```bash
user@pc:/fbbe$ nix --version
nix (Nix) 2.16.1

user@pc:/fbbe$ nix build flake.nix 
error: experimental Nix feature 'nix-command' is disabled; use '--extra-experimental-features nix-command' to override

user@pc:/fbbe$ nix --extra-experimental-features build flake.nix 
warning: unknown experimental feature 'build'
error: 'flake.nix' is not a recognised command
Try 'nix --help' for more information.
```

**Comment by st3b1t** [comment]
> I can merge also the dockerfile, but could you please add a section of the Readme that shows the 2 ways of building the docker?

this work for me:

https://github.com/RCasatta/fbbe/pull/30/commits/d49a5cbcc69a03eba45acc54880a8293d3484213

if you are not going to support docker-compose file I can cut it out from PR and publish it in my public Gist, but I think it's useful to leave it in docker directory

**Comment by RCasatta** [comment]
> I am trying to build this Dockerfile with nix but it doesn't seem like a very understandable tool to use :)

I agree, documentation is scattered around... In this case I think the best source is https://nixos.wiki/wiki/Flakes, so the command would be:
 `nix --experimental-features 'nix-command flakes' build flake.nix `
 But I've set the experimental features in `nix.conf` so I don't have to add those every time
 
 If it works for you and you can please add a Docker section with both methods would be great

**Comment by RCasatta** [comment]
Merged via cherry-pick of 8c03e4227d7883b1d744f7818999e6c3df487cf5 and d49a5cbcc69a03eba45acc54880a8293d3484213

The other 2 commits should not be in the MR

Thanks

**Pull request closed without merging**
